### ISSUE TITLE
 Delete Product

### ISSUE THREAD

**Issue by LukacsG1987** [nagydani98/EvosoftInventoryManager#1]
- [x] Provide product name from console for deletion
- [x] Search product by name
- [x] Execute deletion in xml #

**Comment by Mlaszlo95** [comment]
https://pastebin.com/n0kEGAc3
Valamiért nem töröl. Passz azt még ki kell találnom, illetve még én adom meg az értéket, és nem beolvasom. Nos bár az már pár sor.
